name: Create a cherrypick Demo release

on:
  push:
    branches:
      - release/*

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          versioning-strategy: always-bump-patch
          default-branch: ${{ github.ref_name }} 
